#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#define INPUT_SIZE 1000
#define INPUT_BUFFER_SIZE 1000
#define INPUT_BUFFER_TYPE char
#define INPUT_BUFFER_INDEX(i) (i)
#define INPUT_BUFFER_APPEND(input_buffer, c) (input_buffer)[INPUT_BUFFER_INDEX(i)] = c
#define INPUT_BUFFER_AT(input_buffer, i) (input_buffer)[INPUT_BUFFER_INDEX(i)]
#define INPUT_BUFFER_LENGTH(input_buffer) (i)
#define INPUT_BUFFER_IS_EMPTY(input_buffer) (INPUT_BUFFER_LENGTH(input_buffer) == 0)
#define INPUT_BUFFER_IS_FULL(input_buffer) (INPUT_BUFFER_LENGTH(input_buffer) == INPUT_BUFFER_SIZE)
#define INPUT_BUFFER_PUSH(input_buffer, c) do { INPUT_BUFFER_APPEND(input_buffer, c); } while (0)
#define INPUT_BUFFER_POP(input_buffer) (INPUT_BUFFER_AT(input_buffer, --INPUT_BUFFER_LENGTH(input_buffer)))
#define INPUT_BUFFER_PEEK(input_buffer) (INPUT_BUFFER_AT(input_buffer, INPUT_BUFFER_LENGTH(input_buffer) - 1))
#define INPUT_BUFFER_CLEAR(input_buffer) (INPUT_BUFFER_LENGTH(input_buffer) = 0)
#define INPUT_BUFFER_INIT(input_buffer) do { INPUT_BUFFER_CLEAR(input_buffer); } while (0)
#define INPUT_BUFFER_READ_CHAR(input_buffer) do { int c = getchar(); if (c != EOF) { INPUT_BUFFER_PUSH(input_buffer, c); } } while (0)
#define INPUT_BUFFER_UNREAD_CHAR(input_buffer) do { INPUT_BUFFER_LENGTH(input_buffer)++; } while (0)
#define INPUT_BUFFER_READ_LINE(input_buffer) do { int c; while ((c = getchar()) != EOF && c != '\n') { INPUT_BUFFER_PUSH(input_buffer, c); } if (c == '\n') { INPUT_BUFFER_PUSH(input_buffer, c); } } while (0)
#define INPUT_BUFFER_READ_INTEGER(input_buffer, integer) do { int sign = 1, i = 0; char c; while (INPUT_BUFFER_IS_EMPTY(input_buffer)) { INPUT_BUFFER_READ_CHAR(input_buffer); } if (INPUT_BUFFER_PEEK(input_buffer) == '-') { sign = -1; INPUT_BUFFER_POP(input_buffer); } while (!INPUT_BUFFER_IS_EMPTY(input_buffer) && INPUT_BUFFER_PEEK(input_buffer) >= '0' && INPUT_BUFFER_PEEK(input_buffer) <= '9') { i = i * 10 + INPUT_BUFFER_PEEK(input_buffer) - '0'; INPUT_BUFFER_POP(input_buffer); } integer = sign * i; } while (0)
#define INPUT_BUFFER_READ_REAL(input_buffer, real) do { int sign = 1, i = 0, f = 0, e = 0, e_sign = 1; char c; while (INPUT_BUFFER_IS_EMPTY(input_buffer)) { INPUT_BUFFER_READ_CHAR(input_buffer); } if (INPUT_BUFFER_PEEK(input_buffer) == '-') { sign = -1; INPUT_BUFFER_POP(input_buffer); } while (!INPUT_BUFFER_IS_EMPTY(input_buffer) && INPUT_BUFFER_PEEK(input_buffer) >= '0' && INPUT_BUFFER_PEEK(input_buffer) <= '9') { i = i * 10 + INPUT_BUFFER_PEEK(input_buffer) - '0'; INPUT_BUFFER_POP(input_buffer); } if (INPUT_BUFFER_PEEK(input_buffer) == '.') { INPUT_BUFFER_POP(input_buffer); } while (!INPUT_BUFFER_IS_EMPTY(input_buffer) && INPUT_BUFFER_PEEK(input_buffer) >= '0' && INPUT_BUFFER_PEEK(input_buffer) <= '9') { f = f * 10 + INPUT_BUFFER_PEEK(input_buffer) - '0'; INPUT_BUFFER_POP(input_buffer); } if (INPUT_BUFFER_PEEK(input_buffer) == 'e' || INPUT_BUFFER_PEEK(input_buffer) == 'E') { INPUT_BUFFER_POP(input_buffer); if (INPUT_BUFFER_PEEK(input_buffer) == '-') { e_sign = -1; INPUT_BUFFER_POP(input_buffer); } while (!INPUT_BUFFER_IS_EMPTY(input_buffer) && INPUT_BUFFER_PEEK(input_buffer) >= '0' && INPUT_BUFFER_PEEK(input_buffer) <= '9') { e = e * 10 + INPUT_BUFFER_PEEK(input_buffer) - '0'; INPUT_BUFFER_POP(input_buffer); } } real = (double) sign * (i + f / pow(10, f)) * pow(10, e_sign * e); } while (0)
#define INPUT_BUFFER_READ_STRING(input_buffer, string, size) do { int i = 0; char c; while (INPUT_BUFFER_IS_EMPTY(input_buffer)) { INPUT_BUFFER_READ_CHAR(input_buffer); } while (!INPUT_BUFFER_IS_EMPTY(input_buffer) && i < size - 1 && (c = INPUT_BUFFER_PEEK(input_buffer)) != EOF && c != '\n') { string[i++] = c; INPUT_BUFFER_POP(input_buffer); } string[i] = '\0'; } while (0)
#define INPUT_BUFFER_READ_LINE_AS_INTEGER(input_buffer, integer) do { INPUT_BUFFER_READ_LINE(input_buffer); INPUT_BUFFER_READ_INTEGER(input_buffer, integer); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_REAL(input_buffer, real) do { INPUT_BUFFER_READ_LINE(input_buffer); INPUT_BUFFER_READ_REAL(input_buffer, real); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_STRING(input_buffer, string, size) do { INPUT_BUFFER_READ_LINE(input_buffer); INPUT_BUFFER_READ_STRING(input_buffer, string, size); } while (0)
#define INPUT_BUFFER_READ_CHARS(input_buffer, string, size) do { int i = 0; char c; while (INPUT_BUFFER_IS_EMPTY(input_buffer)) { INPUT_BUFFER_READ_CHAR(input_buffer); } while (!INPUT_BUFFER_IS_EMPTY(input_buffer) && i < size - 1 && (c = INPUT_BUFFER_PEEK(input_buffer)) != EOF) { string[i++] = c; INPUT_BUFFER_POP(input_buffer); } string[i] = '\0'; } while (0)
#define INPUT_BUFFER_READ_INTEGERS(input_buffer, integers, size) do { int i = 0; int integer; while (INPUT_BUFFER_IS_EMPTY(input_buffer)) { INPUT_BUFFER_READ_CHAR(input_buffer); } while (!INPUT_BUFFER_IS_EMPTY(input_buffer) && i < size && (INPUT_BUFFER_READ_INTEGER(input_buffer, integer), 1)) { integers[i++] = integer; } } while (0)
#define INPUT_BUFFER_READ_REALS(input_buffer, reals, size) do { int i = 0; double real; while (INPUT_BUFFER_IS_EMPTY(input_buffer)) { INPUT_BUFFER_READ_CHAR(input_buffer); } while (!INPUT_BUFFER_IS_EMPTY(input_buffer) && i < size && (INPUT_BUFFER_READ_REAL(input_buffer, real), 1)) { reals[i++] = real; } } while (0)
#define INPUT_BUFFER_READ_STRINGS(input_buffer, strings, size) do { int i = 0; char string[INPUT_SIZE]; while (INPUT_BUFFER_IS_EMPTY(input_buffer)) { INPUT_BUFFER_READ_CHAR(input_buffer); } while (!INPUT_BUFFER_IS_EMPTY(input_buffer) && i < size && (INPUT_BUFFER_READ_STRING(input_buffer, string, INPUT_SIZE), 1)) { strings[i++] = string; } } while (0)
#define INPUT_BUFFER_READ_LINE_AS_INTEGERS(input_buffer, integers, size) do { INPUT_BUFFER_READ_LINE(input_buffer); INPUT_BUFFER_READ_INTEGERS(input_buffer, integers, size); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_REALS(input_buffer, reals, size) do { INPUT_BUFFER_READ_LINE(input_buffer); INPUT_BUFFER_READ_REALS(input_buffer, reals, size); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_STRINGS(input_buffer, strings, size) do { INPUT_BUFFER_READ_LINE(input_buffer); INPUT_BUFFER_READ_STRINGS(input_buffer, strings, size); } while (0)
#define INPUT_BUFFER_READ_CHARS_AS_INTEGER(input_buffer, integer) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%d", &integer); } while (0)
#define INPUT_BUFFER_READ_CHARS_AS_REAL(input_buffer, real) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%lf", &real); } while (0)
#define INPUT_BUFFER_READ_CHARS_AS_STRING(input_buffer, string, size) do { INPUT_BUFFER_READ_CHARS(input_buffer, string, size); } while (0)
#define INPUT_BUFFER_READ_CHARS_AS_INTEGERS(input_buffer, integers, size) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%d %d %d %d %d %d %d %d %d %d", &integers[0], &integers[1], &integers[2], &integers[3], &integers[4], &integers[5], &integers[6], &integers[7], &integers[8], &integers[9]); } while (0)
#define INPUT_BUFFER_READ_CHARS_AS_REALS(input_buffer, reals, size) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%lf %lf %lf %lf %lf %lf %lf %lf %lf %lf", &reals[0], &reals[1], &reals[2], &reals[3], &reals[4], &reals[5], &reals[6], &reals[7], &reals[8], &reals[9]); } while (0)
#define INPUT_BUFFER_READ_CHARS_AS_STRINGS(input_buffer, strings, size) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%s %s %s %s %s %s %s %s %s %s", &strings[0], &strings[1], &strings[2], &strings[3], &strings[4], &strings[5], &strings[6], &strings[7], &strings[8], &strings[9]); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_CHARS(input_buffer, string, size) do { INPUT_BUFFER_READ_LINE(input_buffer); INPUT_BUFFER_READ_CHARS(input_buffer, string, size); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_CHARS_AS_INTEGER(input_buffer, integer) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_LINE_AS_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%d", &integer); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_CHARS_AS_REAL(input_buffer, real) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_LINE_AS_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%lf", &real); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_CHARS_AS_STRING(input_buffer, string, size) do { INPUT_BUFFER_READ_LINE_AS_CHARS(input_buffer, string, size); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_CHARS_AS_INTEGERS(input_buffer, integers, size) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_LINE_AS_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%d %d %d %d %d %d %d %d %d %d", &integers[0], &integers[1], &integers[2], &integers[3], &integers[4], &integers[5], &integers[6], &integers[7], &integers[8], &integers[9]); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_CHARS_AS_REALS(input_buffer, reals, size) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_LINE_AS_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%lf %lf %lf %lf %lf %lf %lf %lf %lf %lf", &reals[0], &reals[1], &reals[2], &reals[3], &reals[4], &reals[5], &reals[6], &reals[7], &reals[8], &reals[9]); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_CHARS_AS_STRINGS(input_buffer, strings, size) do { char string[INPUT_SIZE]; INPUT_BUFFER_READ_LINE_AS_CHARS(input_buffer, string, INPUT_SIZE); sscanf(string, "%s %s %s %s %s %s %s %s %s %s", &strings[0], &strings[1], &strings[2], &strings[3], &strings[4], &strings[5], &strings[6], &strings[7], &strings[8], &strings[9]); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_INTEGER_ARRAY(input_buffer, array, size) do { int i; INPUT_BUFFER_READ_LINE_AS_INTEGERS(input_buffer, array, size); for (i = 0; i < size; i++) { printf("%d ", array[i]); } printf("\n"); } while (0)
#define INPUT_BUFFER_READ_LINE_AS_REAL_ARRAY(input_buffer, array, size) do { int i; INPUT_BUFFER_READ_LINE_AS_REALS(input_buffer, array, size); for (i = 0; i < size; i++) { printf("%lf ", array[i]); }