// Initialize an empty list 'l' to store the generated numbers
List<Integer> l = new ArrayList<Integer>();

// Set the limit value for the generated numbers
int limit = 10000000000;

// Function definition to generate numbers recursively
void gen(int number, int four, int seven) {
    // Base case: if the number is greater than the limit, return
    if (number > limit) {
        return;
    }

    // Recursive case 1: if the number is positive and four is equal to seven, append it to the list 'l'
    if (number > 0 && four == seven) {
        l.add(number);
    }

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and'seven'
    gen(number * 10 + 4, four + 1, seven);

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and'seven'
    gen(number * 10 + 7, four, seven + 1);
}

// Main function definition
public static void main(String[] args) {
    // Call the 'gen' function with initial values of 0, 0, and 0
    gen(0, 0, 0);

    // Sort the list 'l' in ascending order
    Collections.sort(l);

    // Read the input number 'n' from the user
    int n = Integer.parseInt(args[0]);

    // Initialize the answer variable 'ans' to 0
    int ans = 0;

    // Iterate through the sorted list 'l' and find the first number that is greater than or equal to 'n'
    for (int val : l) {
        if (val >= n) {
            // Update the answer variable 'ans' with the found number and break the loop
            ans = val;
            break;
        }
    }

    // Print the answer
    System.out.println(ans);
}

