
from itertools import *

# Step 1: Import the product function from the itertools module
# The product function is used to generate the Cartesian product of input iterables.

N = int(input())

# Step 2: Take an integer input N from the user
# This value determines the range of numbers in the list N_list

x = 1

# Step 3: Initialize a variable x to 1
# This variable is used in the list comprehension to generate the list N_list

N_list = [x+1 for x in range(N)]

# Step 4: Create a list N_list that contains numbers from 1 to N
# The list comprehension iterates over a range from 0 to N-1 and adds 1 to each element

n = list(product(N_list, repeat=3))

# Step 5: Generate a list n using the product function with N_list and a repeat parameter of 3
# The product function generates the Cartesian product of N_list taken 3 times

m = len(n)

# Step 6: Calculate the length of n and store it in m
# The length of n represents the number of possible combinations

print(m)

# Step 7: Print the value of m
# This value indicates the number of combinations generated by the product function

