
# This line reads a string input from the user and stores it in the variable `strn`.
strn = input()

# This line converts the string input to an integer and stores it in the variable `n`.
n = int(strn)

# This list contains the characters "3", "5", and "7" which will be used to generate numbers.
shichigolist = ["3","5","7"]

# This creates a list of empty lists, where each sublist will store numbers generated by the algorithm.
# The number of sublists is equal to the length of the input string `strn`.
shichigo = [[] for _ in range(len(strn))]

# This loop iterates over the length of the input string.
for i in range(len(strn)):
    # For the first iteration (i == 0), it appends each character in `shichigolist` to the first sublist.
    if i == 0:
        for j in shichigolist:
            shichigo[i].append(j)
    # For subsequent iterations, it appends combinations of the previous sublist with each character in `shichigolist`.
    else:
        for j in shichigo[i-1]:
            for k in shichigolist:
                shichigo[i].append(j+k)

# This variable stores the index of the last sublist in `shichigo`.
target = len(strn)-1

# This nested loop iterates over each sublist and its elements.
for i in range(len(strn)):
    for j in shichigo[i][:]:
        # For the last sublist (target), it removes elements if they are greater than `n` or do not contain "3", "5", or "7".
        if i == target:
            if int(j) > n:
                shichigo[target].remove(j)
            elif j.count("3")==0 or j.count("5")==0 or j.count("7")==0:
                shichigo[target].remove(j)
        # For other sublists, it removes elements that do not contain "3", "5", or "7".
        else:
            if j.count("3")==0 or j.count("5")==0 or j.count("7")==0:
                shichigo[i].remove(j)

# This line prints the sum of the lengths of all sublists in `shichigo`, which represents the count of valid numbers.
print(sum([len(shichigo[i]) for i in range(len(strn))]))

