#include <stdio.h>
#include <stdlib.h>

// Function definition to generate numbers recursively
void gen(int number, int four, int seven)
{
    // Base case: if the number is greater than the limit, return
    if (number > 10000000000)
        return;

    // Recursive case 1: if the number is positive and four is equal to seven, print it
    if (number > 0 && four == seven)
        printf("%d\n", number);

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and'seven'
    gen(number * 10 + 4, four + 1, seven);

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and'seven'
    gen(number * 10 + 7, four, seven + 1);
}

// Main function definition
int main()
{
    // Call the 'gen' function with initial values of 0, 0, and 0
    gen(0, 0, 0);

    // Read the input number 'n' from the user
    int n;
    scanf("%d", &n);

    // Initialize the answer variable 'ans' to 0
    int ans = 0;

    // Iterate through the sorted list 'l' and find the first number that is greater than or equal to 'n'
    for (int val = 0; val < 10000000000; val++)
    {
        if (val >= n)
        {
            // Update the answer variable 'ans' with the found number and break the loop
            ans = val;
            break;
        }
    }

    // Print the answer
    printf("%d\n", ans);

    // Return from the main function
    return 0;
}

