#include <stdio.h>
#include <stdlib.h>

// Function to generate numbers recursively
void gen(int number, int four, int seven, int *l, int limit) {
    // Base case: if the number is greater than the limit, return
    if (number > limit) {
        return;
    }

    // Recursive case 1: if the number is positive and four is equal to seven, append it to the list 'l'
    if (number > 0 && four == seven) {
        l[number] = 1;
    }

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and 'seven'
    gen(number * 10 + 4, four + 1, seven, l, limit);

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and 'seven'
    gen(number * 10 + 7, four, seven + 1, l, limit);
}

// Main function definition
int main() {
    // Initialize an empty list 'l' to store the generated numbers
    int l[10000000000];

    // Set the limit value for the generated numbers
    int limit = 10000000000;

    // Call the 'gen' function with initial values of 0, 0, and 0
    gen(0, 0, 0, l, limit);

    // Sort the list 'l' in ascending order
    int i, j;
    for (i = 0; i < limit; i++) {
        for (j = i + 1; j < limit; j++) {
            if (l[i] > l[j]) {
                int temp = l[i];
                l[i] = l[j];
                l[j] = temp;
            }
        }
    }

    // Read the input number 'n' from the user
    int n;
    scanf("%d", &n);

    // Initialize the answer variable 'ans' to 0
    int ans = 0;

    // Iterate through the sorted list 'l' and find the first number that is greater than or equal to 'n'
    for (i = 0; i < limit; i++) {
        if (l[i] >= n) {
            // Update the answer variable 'ans' with the found number and break the loop
            ans = l[i];
            break;
        }
    }

    // Print the answer
    printf("%d\n", ans);

    return 0;
}

