
// C++ code generated by Go generate command.
// This line is a Go generate command to download the problem statement from AtCoder.
// It is not necessary to understand its functionality for the given code.

#include <bits/stdc++.h>

using namespace std;

int main() {
  ios::sync_with_stdio(false);
  cin.tie(0);

  int n;
  cin >> n;
  vector<int> heights(n);
  for (int i = 0; i < n; i++) {
    cin >> heights[i];
  }

  vector<int> t(n, 1e9);
  t[0] = 0;
  for (int i = 1; i < n; i++) {
    int prev_index_cost = t[i - 1];
    if (heights[i] - heights[i - 1] < 0) {
      prev_index_cost += heights[i] - heights[i - 1];
    } else {
      prev_index_cost -= heights[i] - heights[i - 1];
    }
    if (i - 2 >= 0) {
      int prev_prev_index_cost = t[i - 2];
      if (heights[i] - heights[i - 2] < 0) {
        prev_prev_index_cost += heights[i] - heights[i - 2];
      } else {
        prev_prev_index_cost -= heights[i] - heights[i - 2];
      }
      t[i] = min(prev_index_cost, prev_prev_index_cost);
    } else {
      t[i] = prev_index_cost;
    }
  }

  cout << t[n - 1] << endl;

  return 0;
}

// The following comment can be added at the end of the code.

