#include <bits/stdc++.h>
using namespace std;

#define INT(x) atoi(x.c_str())
#define LONG(x) atol(x.c_str())
#define LL(x) atoll(x.c_str())
#define MAP(x, y) map<x, y>
#define PB push_back
#define PQ priority_queue
#define MP make_pair
#define SQ(x) sqrt(x)
#define MOD(x) (x % MOD)
#define INF 1000000007
#define PI 3.14159265358979323846
#define PER(i, n) for (int i = 0; i < n; ++i)
#define REP(i, n) for (int i = 1; i <= n; ++i)
#define REP1(i, n) for (int i = 1; i <= n; ++i)
#define REP1A(i, n) for (int i = 0; i < n; ++i)
#define REP2(i, s, n) for (int i = s; i <= n; ++i)
#define REP2A(i, s, n) for (int i = s; i < n; ++i)
#define REP3(i, s, n) for (int i = s; i >= n; --i)
#define REP3A(i, s, n) for (int i = s; i > n; --i)
#define REP4(i, s, n, d) for (int i = s; i <= n; i += d)
#define REP4A(i, s, n, d) for (int i = s; i < n; i += d)
#define REP5(i, s, n, d1, d2) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2)
#define REP6(i, s, n, d1, d2, d3) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3)
#define REP7(i, s, n, d1, d2, d3, d4) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4)
#define REP8(i, s, n, d1, d2, d3, d4, d5) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5)
#define REP9(i, s, n, d1, d2, d3, d4, d5, d6) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6)
#define REP10(i, s, n, d1, d2, d3, d4, d5, d6, d7) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7)
#define REP11(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8)
#define REP12(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9)
#define REP13(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10)
#define REP14(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11)
#define REP15(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12)
#define REP16(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12) for (int x = w; x <= n; x += d13)
#define REP17(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12) for (int x = w; x <= n; x += d13) for (int y = x; y <= n; y += d14)
#define REP18(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12) for (int x = w; x <= n; x += d13) for (int y = x; y <= n; y += d14) for (int z = y; z <= n; z += d15)
#define REP19(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12) for (int x = w; x <= n; x += d13) for (int y = x; y <= n; y += d14) for (int z = y; z <= n; z += d15) for (int a = z; a <= n; a += d16)
#define REP20(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12) for (int x = w; x <= n; x += d13) for (int y = x; y <= n; y += d14) for (int z = y; z <= n; z += d15) for (int a = z; a <= n; a += d16) for (int b = a; b <= n; b += d17)
#define REP21(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12) for (int x = w; x <= n; x += d13) for (int y = x; y <= n; y += d14) for (int z = y; z <= n; z += d15) for (int a = z; a <= n; a += d16) for (int b = a; b <= n; b += d17) for (int c = b; c <= n; c += d18)
#define REP22(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18, d19) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12) for (int x = w; x <= n; x += d13) for (int y = x; y <= n; y += d14) for (int z = y; z <= n; z += d15) for (int a = z; a <= n; a += d16) for (int b = a; b <= n; b += d17) for (int c = b; c <= n; c += d18) for (int d = c; d <= n; d += d19)
#define REP23(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18, d19, d20) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12) for (int x = w; x <= n; x += d13) for (int y = x; y <= n; y += d14) for (int z = y; z <= n; z += d15) for (int a = z; a <= n; a += d16) for (int b = a; b <= n; b += d17) for (int c = b; c <= n; c += d18) for (int d = c; d <= n; d += d19) for (int e = d; e <= n; e += d20)
#define REP24(i, s, n, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18, d19, d20, d21) for (int i = s; i <= n; i += d1) for (int j = i; j <= n; j += d2) for (int k = j; k <= n; k += d3) for (int l = k; l <= n; l += d4) for (int m = l; m <= n; m += d5) for (int p = m; p <= n; p += d6) for (int q = p; q <= n; q += d7) for (int r = q; r <= n; r += d8) for (int t = r; t <= n; t += d9) for (int u = t; u <= n; u += d10) for (int v = u; v <= n; v += d11) for (int w = v; w <= n; w += d12) for (int x = w; x <= n; x += d13) for (int y = x; y <= n; y += d14) for (int z = y; z <= n; z += d15) for (int a = z; a <= n; a += d16) for (int b = a; b <= n; b += d17) for (int c = b; c <= n; c += d18) for (int d = c; d <= n; d += d19) for (int e = d; e <= n; e += d20) for (int f = e; f <= n; f += d21)
#define REP25(i, s, n, d1, d2, 