#include <stdio.h>
#include <stdlib.h>

#define LIMIT 10000000000

// Initialize an empty list 'l' to store the generated numbers
long long *l;
int l_size = 0;
int l_capacity = 1000000; // Initial capacity for the list

// Function to append a number to the list
void append_to_list(long long number) {
    if (l_size >= l_capacity) {
        l_capacity *= 2;
        l = realloc(l, l_capacity * sizeof(long long));
    }
    l[l_size++] = number;
}

// Function definition to generate numbers recursively
void gen(long long number, int four, int seven) {
    // Base case: if the number is greater than the limit, return
    if (number > LIMIT) {
        return;
    }

    // Recursive case 1: if the number is positive and four is equal to seven, append it to the list 'l'
    if (number > 0 && four == seven) {
        append_to_list(number);
    }

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and 'seven'
    gen(number * 10 + 4, four + 1, seven);
    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and 'seven'
    gen(number * 10 + 7, four, seven + 1);
}

// Function to compare two long long integers for qsort
int compare(const void *a, const void *b) {
    return (*(long long *)a - *(long long *)b);
}

// Main function definition
int main() {
    // Allocate initial memory for the list
    l = malloc(l_capacity * sizeof(long long));

    // Call the 'gen' function with initial values of 0, 0, and 0
    gen(0, 0, 0);

    // Sort the list 'l' in ascending order
    qsort(l, l_size, sizeof(long long), compare);

    // Read the input number 'n' from the user
    long long n;
    scanf("%lld", &n);

    // Initialize the answer variable 'ans' to 0
    long long ans = 0;

    // Iterate through the sorted list 'l' and find the first number that is greater than or equal to 'n'
    for (int i = 0; i < l_size; i++) {
        if (l[i] >= n) {
            // Update the answer variable 'ans' with the found number and break the loop
            ans = l[i];
            break;
        }
    }

    // Print the answer
    printf("%lld\n", ans);

    // Free the allocated memory
    free(l);

    return 0;
}

// <END-OF-CODE>
