#include <stdio.h>
#include <stdlib.h>

// Initialize an empty list 'l' to store the generated numbers
int l[1000000];
int l_size = 0;

// Set the limit value for the generated numbers
long long limit = 10000000000;

// Function definition to generate numbers recursively
void gen(int number, int four, int seven) {
    // Base case: if the number is greater than the limit, return
    if (number > limit) {
        return;
    }

    // Recursive case 1: if the number is positive and four is equal to seven, append it to the list 'l'
    if (number > 0 && four == seven) {
        l[l_size++] = number;
    }

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and 'seven'
    gen(number * 10 + 4, four + 1, seven);

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and 'seven'
    gen(number * 10 + 7, four, seven + 1);
}

// Main function definition
int main() {
    // Call the 'gen' function with initial values of 0, 0, and 0
    gen(0, 0, 0);

    // Sort the list 'l' in ascending order
    qsort(l, l_size, sizeof(int), (int (*)(const void *, const void *))compare);

    // Read the input number 'n' from the user
    int n;
    scanf("%d", &n);

    // Initialize the answer variable 'ans' to 0
    int ans = 0;

    // Iterate through the sorted list 'l' and find the first number that is greater than or equal to 'n'
    for (int i = 0; i < l_size; i++) {
        if (l[i] >= n) {
            // Update the answer variable 'ans' with the found number and break the loop
            ans = l[i];
            break;
        }
    }

    // Print the answer
    printf("%d\n", ans);

    return 0;
}

// Comparison function for qsort
int compare(const void *a, const void *b) {
    return (*(int *)a - *(int *)b);
}
