
#include <stdio.h>
#include <stdlib.h>

// Function definition to generate numbers recursively
void gen(long number, int four, int seven, long *l, int limit) {
    // Base case: if the number is greater than the limit, return
    if (number > limit) {
        return;
    }

    // Recursive case 1: if the number is positive and four is equal to seven, append it to the list 'l'
    if (number > 0 && four == seven) {
        l[0]++;
        l[l[0]] = number;
    }

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and'seven'
    gen(number * 10 + 4, four + 1, seven, l, limit);

    // Recursive call for the next number generated by adding 10 to the current number and updating the values of 'four' and'seven'
    gen(number * 10 + 7, four, seven + 1, l, limit);
}

// Main function definition
int main() {
    // Initialize an empty list 'l' to store the generated numbers
    long l[10000000000];
    l[0] = 0;

    // Set the limit value for the generated numbers
    int limit = 10000000000;

    // Call the 'gen' function with initial values of 0, 0, and 0
    gen(0, 0, 0, l, limit);

    // Sort the list 'l' in ascending order
    qsort(l + 1, l[0], sizeof(long));

    // Read the input number 'n' from the user
    long n;
    scanf("%ld", &n);

    // Initialize the answer variable 'ans' to 0
    long ans = 0;

    // Iterate through the sorted list 'l' and find the first number that is greater than or equal to 'n'
    for (int i = 1; i <= l[0]; i++) {
        if (l[i] >= n) {
            // Update the answer variable 'ans' with the found number and break the loop
            ans = l[i];
            break;
        }
    }

    // Print the answer
    printf("%ld\n", ans);

    return 0;
}

// Translate the above C code to Java and end with comment "